version: "3.7"

services:
  app:
    container_name: fastapi-project-structure
    image: fastapi-project-structure:latest
    ports:
      - "8081:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY:-secret-key}
      - DATABASE_URL=${DATABASE_URL:-postgresql://pguser:pgpassword@postgres/fastapi}
    depends_on:
      - postgres

  postgres:
    image: postgres:14.11-alpine
    volumes:
      - fastapi_pg_data:/var/lib/postgresql/data
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pguser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - POSTGRES_DB=${POSTGRES_DB:-fastapi}

volumes:
  fastapi_pg_data:
    driver: "local"
