version: 1
disable_existing_loggers: False
filters:
  correlation_id:
    "()": asgi_correlation_id.CorrelationIdFilter
    uuid_length: 32
    default_value: "-"

formatters:
  app:
    format: "%(asctime)s - %(name)s - %(levelname)s - [%(correlation_id)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  uvcorn_error:
    "()": uvicorn.logging.DefaultFormatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  uvcorn_access:
    "()": uvicorn.logging.AccessFormatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  app:
    class: logging.StreamHandler
    level: DEBUG
    filters:
      - correlation_id
    formatter: app
    stream: ext://sys.stdout
  uvcorn_error:
    class: logging.StreamHandler
    formatter: uvcorn_error
    stream: ext://sys.stderr
  uvcorn_access:
    class: logging.StreamHandler
    formatter: uvcorn_access
    stream: ext://sys.stdout

loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - uvcorn_error
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - uvcorn_access
    propagate: no

root:
  level: DEBUG
  handlers: [app]
